apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-b-demo
  namespace: team-b
  labels:
    app: team-b-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team-b-demo
  template:
    metadata:
      labels:
        app: team-b-demo
    spec:
      serviceAccountName: team-b-app-sa
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          env:
            - name: APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: team-b-app-secret
                  key: APP_TOKEN
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: team-b-app-secret
                  key: APP_ENV
